[package]
name = "luals-gen"
version = "0.1.0"
edition = "2021"

[dependencies]
luals-gen-derive = { path = "./luals-gen-derive" }

[workspace]
members = [".", "luals-gen-derive"]

[dev-dependencies]
serde = { version = "1", features = ["derive"] }
serde_json = "1"
