[package]
name = "luals-gen-derive"
version = "0.1.0"
edition = "2021"

[dependencies]
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
convert_case = "0.6.0"
proc-macro2 = "*"

[lib]
proc-macro = true
